package festivalOverview;
// Generated 21-apr-2013 14:27:53 by Hibernate Tools 3.2.1.GA



/**
 * Campingsperfestival generated by hbm2java
 */
public class Campingsperfestival  implements java.io.Serializable {


     private CampingsperfestivalId id;
     private Festivals festivals;

    public Campingsperfestival() {
    }

    public Campingsperfestival(CampingsperfestivalId id, Festivals festivals) {
       this.id = id;
       this.festivals = festivals;
    }
   
    public CampingsperfestivalId getId() {
        return this.id;
    }
    
    public void setId(CampingsperfestivalId id) {
        this.id = id;
    }
    public Festivals getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Festivals festivals) {
        this.festivals = festivals;
    }




}


