package festivalOverview;
// Generated 21-apr-2013 14:27:53 by Hibernate Tools 3.2.1.GA



/**
 * CampingsperfestivalId generated by hbm2java
 */
public class CampingsperfestivalId  implements java.io.Serializable {


     private int festId;
     private int campId;

    public CampingsperfestivalId() {
    }

    public CampingsperfestivalId(int festId, int campId) {
       this.festId = festId;
       this.campId = campId;
    }
   
    public int getFestId() {
        return this.festId;
    }
    
    public void setFestId(int festId) {
        this.festId = festId;
    }
    public int getCampId() {
        return this.campId;
    }
    
    public void setCampId(int campId) {
        this.campId = campId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CampingsperfestivalId) ) return false;
		 CampingsperfestivalId castOther = ( CampingsperfestivalId ) other; 
         
		 return (this.getFestId()==castOther.getFestId())
 && (this.getCampId()==castOther.getCampId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFestId();
         result = 37 * result + this.getCampId();
         return result;
   }   


}


