package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Campings generated by hbm2java
 */
public class Campings  implements java.io.Serializable {


     private Integer campId;
     private String campAdres;
     private int campCap;
     private Set<Festivals> festivalses = new HashSet<Festivals>(0);
     private Set<Facpercamp> facpercamps = new HashSet<Facpercamp>(0);

    public Campings() {
    }

	
    public Campings(String campAdres, int campCap) {
        this.campAdres = campAdres;
        this.campCap = campCap;
    }
    public Campings(String campAdres, int campCap, Set<Festivals> festivalses, Set<Facpercamp> facpercamps) {
       this.campAdres = campAdres;
       this.campCap = campCap;
       this.festivalses = festivalses;
       this.facpercamps = facpercamps;
    }
   
    public Integer getCampId() {
        return this.campId;
    }
    
    public void setCampId(Integer campId) {
        this.campId = campId;
    }
    public String getCampAdres() {
        return this.campAdres;
    }
    
    public void setCampAdres(String campAdres) {
        this.campAdres = campAdres;
    }
    public int getCampCap() {
        return this.campCap;
    }
    
    public void setCampCap(int campCap) {
        this.campCap = campCap;
    }
    public Set<Festivals> getFestivalses() {
        return this.festivalses;
    }
    
    public void setFestivalses(Set<Festivals> festivalses) {
        this.festivalses = festivalses;
    }
    public Set<Facpercamp> getFacpercamps() {
        return this.facpercamps;
    }
    
    public void setFacpercamps(Set<Facpercamp> facpercamps) {
        this.facpercamps = facpercamps;
    }




}


