package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Faciliteiten generated by hbm2java
 */
public class Faciliteiten  implements java.io.Serializable {


     private Integer facId;
     private String facOmschr;
     private Double facEenhprijs;
     private Set<Facpercamp> facpercamps = new HashSet<Facpercamp>(0);

    public Faciliteiten() {
    }

	
    public Faciliteiten(String facOmschr) {
        this.facOmschr = facOmschr;
    }
    public Faciliteiten(String facOmschr, Double facEenhprijs, Set<Facpercamp> facpercamps) {
       this.facOmschr = facOmschr;
       this.facEenhprijs = facEenhprijs;
       this.facpercamps = facpercamps;
    }
   
    public Integer getFacId() {
        return this.facId;
    }
    
    public void setFacId(Integer facId) {
        this.facId = facId;
    }
    public String getFacOmschr() {
        return this.facOmschr;
    }
    
    public void setFacOmschr(String facOmschr) {
        this.facOmschr = facOmschr;
    }
    public Double getFacEenhprijs() {
        return this.facEenhprijs;
    }
    
    public void setFacEenhprijs(Double facEenhprijs) {
        this.facEenhprijs = facEenhprijs;
    }
    public Set<Facpercamp> getFacpercamps() {
        return this.facpercamps;
    }
    
    public void setFacpercamps(Set<Facpercamp> facpercamps) {
        this.facpercamps = facpercamps;
    }




}


