package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festivals generated by hbm2java
 */
public class Festivals  implements java.io.Serializable {


     private Integer festId;
     private String festNaam;
     private String festLocatie;
     private Date festDatum;
     private byte festDuur;
     private Set<Tickets> ticketses = new HashSet<Tickets>(0);
     private Set<Bandsperfestival> bandsperfestivals = new HashSet<Bandsperfestival>(0);
     private Set<Campings> campingses = new HashSet<Campings>(0);
     private Set<Tickettypesperfestival> tickettypesperfestivals = new HashSet<Tickettypesperfestival>(0);

    public Festivals() {
    }

	
    public Festivals(String festNaam, String festLocatie, Date festDatum, byte festDuur) {
        this.festNaam = festNaam;
        this.festLocatie = festLocatie;
        this.festDatum = festDatum;
        this.festDuur = festDuur;
    }
    public Festivals(String festNaam, String festLocatie, Date festDatum, byte festDuur, Set<Tickets> ticketses, Set<Bandsperfestival> bandsperfestivals, Set<Campings> campingses, Set<Tickettypesperfestival> tickettypesperfestivals) {
       this.festNaam = festNaam;
       this.festLocatie = festLocatie;
       this.festDatum = festDatum;
       this.festDuur = festDuur;
       this.ticketses = ticketses;
       this.bandsperfestivals = bandsperfestivals;
       this.campingses = campingses;
       this.tickettypesperfestivals = tickettypesperfestivals;
    }
   
    public Integer getFestId() {
        return this.festId;
    }
    
    public void setFestId(Integer festId) {
        this.festId = festId;
    }
    public String getFestNaam() {
        return this.festNaam;
    }
    
    public void setFestNaam(String festNaam) {
        this.festNaam = festNaam;
    }
    public String getFestLocatie() {
        return this.festLocatie;
    }
    
    public void setFestLocatie(String festLocatie) {
        this.festLocatie = festLocatie;
    }
    public Date getFestDatum() {
        return this.festDatum;
    }
    
    public void setFestDatum(Date festDatum) {
        this.festDatum = festDatum;
    }
    public byte getFestDuur() {
        return this.festDuur;
    }
    
    public void setFestDuur(byte festDuur) {
        this.festDuur = festDuur;
    }
    public Set<Tickets> getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set<Tickets> ticketses) {
        this.ticketses = ticketses;
    }
    public Set<Bandsperfestival> getBandsperfestivals() {
        return this.bandsperfestivals;
    }
    
    public void setBandsperfestivals(Set<Bandsperfestival> bandsperfestivals) {
        this.bandsperfestivals = bandsperfestivals;
    }
    public Set<Campings> getCampingses() {
        return this.campingses;
    }
    
    public void setCampingses(Set<Campings> campingses) {
        this.campingses = campingses;
    }
    public Set<Tickettypesperfestival> getTickettypesperfestivals() {
        return this.tickettypesperfestivals;
    }
    
    public void setTickettypesperfestivals(Set<Tickettypesperfestival> tickettypesperfestivals) {
        this.tickettypesperfestivals = tickettypesperfestivals;
    }




}


