package festivalOverview;
// Generated 21-apr-2013 16:18:54 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festivals generated by hbm2java
 */
public class Festivals  implements java.io.Serializable {


     private Integer festId;
     private String festNaam;
     private String festLocatie;
     private Date festDatum;
     private byte festDuur;
     private Set ticketses = new HashSet(0);
     private Set bandsperfestivals = new HashSet(0);
     private Set campingses = new HashSet(0);
     private Set tickettypesperfestivals = new HashSet(0);

    public Festivals() {
    }

	
    public Festivals(String festNaam, String festLocatie, Date festDatum, byte festDuur) {
        this.festNaam = festNaam;
        this.festLocatie = festLocatie;
        this.festDatum = festDatum;
        this.festDuur = festDuur;
    }
    public Festivals(String festNaam, String festLocatie, Date festDatum, byte festDuur, Set ticketses, Set bandsperfestivals, Set campingses, Set tickettypesperfestivals) {
       this.festNaam = festNaam;
       this.festLocatie = festLocatie;
       this.festDatum = festDatum;
       this.festDuur = festDuur;
       this.ticketses = ticketses;
       this.bandsperfestivals = bandsperfestivals;
       this.campingses = campingses;
       this.tickettypesperfestivals = tickettypesperfestivals;
    }
   
    public Integer getFestId() {
        return this.festId;
    }
    
    public void setFestId(Integer festId) {
        this.festId = festId;
    }
    public String getFestNaam() {
        return this.festNaam;
    }
    
    public void setFestNaam(String festNaam) {
        this.festNaam = festNaam;
    }
    public String getFestLocatie() {
        return this.festLocatie;
    }
    
    public void setFestLocatie(String festLocatie) {
        this.festLocatie = festLocatie;
    }
    public Date getFestDatum() {
        return this.festDatum;
    }
    
    public void setFestDatum(Date festDatum) {
        this.festDatum = festDatum;
    }
    public byte getFestDuur() {
        return this.festDuur;
    }
    
    public void setFestDuur(byte festDuur) {
        this.festDuur = festDuur;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }
    public Set getBandsperfestivals() {
        return this.bandsperfestivals;
    }
    
    public void setBandsperfestivals(Set bandsperfestivals) {
        this.bandsperfestivals = bandsperfestivals;
    }
    public Set getCampingses() {
        return this.campingses;
    }
    
    public void setCampingses(Set campingses) {
        this.campingses = campingses;
    }
    public Set getTickettypesperfestivals() {
        return this.tickettypesperfestivals;
    }
    
    public void setTickettypesperfestivals(Set tickettypesperfestivals) {
        this.tickettypesperfestivals = tickettypesperfestivals;
    }




}


