package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Geregistreerdegebruikers generated by hbm2java
 */
public class Geregistreerdegebruikers  implements java.io.Serializable {


     private Integer gebrId;
     private String gebrNaam;
     private String gebrAdres;
     private Date gebrGebDat;
     private Set<Tickets> ticketses = new HashSet<Tickets>(0);

    public Geregistreerdegebruikers() {
    }

	
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat) {
        this.gebrNaam = gebrNaam;
        this.gebrAdres = gebrAdres;
        this.gebrGebDat = gebrGebDat;
    }
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, Set<Tickets> ticketses) {
       this.gebrNaam = gebrNaam;
       this.gebrAdres = gebrAdres;
       this.gebrGebDat = gebrGebDat;
       this.ticketses = ticketses;
    }
   
    public Integer getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(Integer gebrId) {
        this.gebrId = gebrId;
    }
    public String getGebrNaam() {
        return this.gebrNaam;
    }
    
    public void setGebrNaam(String gebrNaam) {
        this.gebrNaam = gebrNaam;
    }
    public String getGebrAdres() {
        return this.gebrAdres;
    }
    
    public void setGebrAdres(String gebrAdres) {
        this.gebrAdres = gebrAdres;
    }
    public Date getGebrGebDat() {
        return this.gebrGebDat;
    }
    
    public void setGebrGebDat(Date gebrGebDat) {
        this.gebrGebDat = gebrGebDat;
    }
    public Set<Tickets> getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set<Tickets> ticketses) {
        this.ticketses = ticketses;
    }




}


