package festivalOverview;
// Generated 21-apr-2013 16:18:54 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Geregistreerdegebruikers generated by hbm2java
 */
public class Geregistreerdegebruikers  implements java.io.Serializable {


     private Integer gebrId;
     private String gebrNaam;
     private String gebrAdres;
     private Date gebrGebDat;
     private String gebrWachtwoord;
     private String gebrEmail;
     private Set ticketses = new HashSet(0);

    public Geregistreerdegebruikers() {
    }

	
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrWachtwoord, String gebrEmail) {
        this.gebrNaam = gebrNaam;
        this.gebrAdres = gebrAdres;
        this.gebrGebDat = gebrGebDat;
        this.gebrWachtwoord = gebrWachtwoord;
        this.gebrEmail = gebrEmail;
    }
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrWachtwoord, String gebrEmail, Set ticketses) {
       this.gebrNaam = gebrNaam;
       this.gebrAdres = gebrAdres;
       this.gebrGebDat = gebrGebDat;
       this.gebrWachtwoord = gebrWachtwoord;
       this.gebrEmail = gebrEmail;
       this.ticketses = ticketses;
    }
   
    public Integer getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(Integer gebrId) {
        this.gebrId = gebrId;
    }
    public String getGebrNaam() {
        return this.gebrNaam;
    }
    
    public void setGebrNaam(String gebrNaam) {
        this.gebrNaam = gebrNaam;
    }
    public String getGebrAdres() {
        return this.gebrAdres;
    }
    
    public void setGebrAdres(String gebrAdres) {
        this.gebrAdres = gebrAdres;
    }
    public Date getGebrGebDat() {
        return this.gebrGebDat;
    }
    
    public void setGebrGebDat(Date gebrGebDat) {
        this.gebrGebDat = gebrGebDat;
    }
    public String getGebrWachtwoord() {
        return this.gebrWachtwoord;
    }
    
    public void setGebrWachtwoord(String gebrWachtwoord) {
        this.gebrWachtwoord = gebrWachtwoord;
    }
    public String getGebrEmail() {
        return this.gebrEmail;
    }
    
    public void setGebrEmail(String gebrEmail) {
        this.gebrEmail = gebrEmail;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


