package festivalOverview;
// Generated 21-apr-2013 14:34:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LoggingBands generated by hbm2java
 */
public class LoggingBands  implements java.io.Serializable {


     private Integer loggingBandId;
     private int bandId;
     private String bandNaam;
     private String bandSoortMuziek;
     private String bandUrl;
     private Date startDate;
     private Date enddate;

    public LoggingBands() {
    }

	
    public LoggingBands(int bandId, String bandNaam, String bandSoortMuziek, String bandUrl) {
        this.bandId = bandId;
        this.bandNaam = bandNaam;
        this.bandSoortMuziek = bandSoortMuziek;
        this.bandUrl = bandUrl;
    }
    public LoggingBands(int bandId, String bandNaam, String bandSoortMuziek, String bandUrl, Date startDate, Date enddate) {
       this.bandId = bandId;
       this.bandNaam = bandNaam;
       this.bandSoortMuziek = bandSoortMuziek;
       this.bandUrl = bandUrl;
       this.startDate = startDate;
       this.enddate = enddate;
    }
   
    public Integer getLoggingBandId() {
        return this.loggingBandId;
    }
    
    public void setLoggingBandId(Integer loggingBandId) {
        this.loggingBandId = loggingBandId;
    }
    public int getBandId() {
        return this.bandId;
    }
    
    public void setBandId(int bandId) {
        this.bandId = bandId;
    }
    public String getBandNaam() {
        return this.bandNaam;
    }
    
    public void setBandNaam(String bandNaam) {
        this.bandNaam = bandNaam;
    }
    public String getBandSoortMuziek() {
        return this.bandSoortMuziek;
    }
    
    public void setBandSoortMuziek(String bandSoortMuziek) {
        this.bandSoortMuziek = bandSoortMuziek;
    }
    public String getBandUrl() {
        return this.bandUrl;
    }
    
    public void setBandUrl(String bandUrl) {
        this.bandUrl = bandUrl;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }




}


