package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LoggingFestivals generated by hbm2java
 */
public class LoggingFestivals  implements java.io.Serializable {


     private Integer festLoggingId;
     private int festId;
     private String festNaam;
     private String festLocatie;
     private Date festDatum;
     private byte festDuur;
     private Date startDate;
     private Date enddate;

    public LoggingFestivals() {
    }

	
    public LoggingFestivals(int festId, String festNaam, String festLocatie, Date festDatum, byte festDuur) {
        this.festId = festId;
        this.festNaam = festNaam;
        this.festLocatie = festLocatie;
        this.festDatum = festDatum;
        this.festDuur = festDuur;
    }
    public LoggingFestivals(int festId, String festNaam, String festLocatie, Date festDatum, byte festDuur, Date startDate, Date enddate) {
       this.festId = festId;
       this.festNaam = festNaam;
       this.festLocatie = festLocatie;
       this.festDatum = festDatum;
       this.festDuur = festDuur;
       this.startDate = startDate;
       this.enddate = enddate;
    }
   
    public Integer getFestLoggingId() {
        return this.festLoggingId;
    }
    
    public void setFestLoggingId(Integer festLoggingId) {
        this.festLoggingId = festLoggingId;
    }
    public int getFestId() {
        return this.festId;
    }
    
    public void setFestId(int festId) {
        this.festId = festId;
    }
    public String getFestNaam() {
        return this.festNaam;
    }
    
    public void setFestNaam(String festNaam) {
        this.festNaam = festNaam;
    }
    public String getFestLocatie() {
        return this.festLocatie;
    }
    
    public void setFestLocatie(String festLocatie) {
        this.festLocatie = festLocatie;
    }
    public Date getFestDatum() {
        return this.festDatum;
    }
    
    public void setFestDatum(Date festDatum) {
        this.festDatum = festDatum;
    }
    public byte getFestDuur() {
        return this.festDuur;
    }
    
    public void setFestDuur(byte festDuur) {
        this.festDuur = festDuur;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }




}


