package festivalOverview;
// Generated 21-apr-2013 15:06:18 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tickettypes generated by hbm2java
 */
public class Tickettypes  implements java.io.Serializable {


     private Integer typId;
     private String typOmschr;
     private double typPrijs;
     private Set<Tickettypesperfestival> tickettypesperfestivals = new HashSet<Tickettypesperfestival>(0);
     private Set<Tickets> ticketses = new HashSet<Tickets>(0);

    public Tickettypes() {
    }

	
    public Tickettypes(String typOmschr, double typPrijs) {
        this.typOmschr = typOmschr;
        this.typPrijs = typPrijs;
    }
    public Tickettypes(String typOmschr, double typPrijs, Set<Tickettypesperfestival> tickettypesperfestivals, Set<Tickets> ticketses) {
       this.typOmschr = typOmschr;
       this.typPrijs = typPrijs;
       this.tickettypesperfestivals = tickettypesperfestivals;
       this.ticketses = ticketses;
    }
   
    public Integer getTypId() {
        return this.typId;
    }
    
    public void setTypId(Integer typId) {
        this.typId = typId;
    }
    public String getTypOmschr() {
        return this.typOmschr;
    }
    
    public void setTypOmschr(String typOmschr) {
        this.typOmschr = typOmschr;
    }
    public double getTypPrijs() {
        return this.typPrijs;
    }
    
    public void setTypPrijs(double typPrijs) {
        this.typPrijs = typPrijs;
    }
    public Set<Tickettypesperfestival> getTickettypesperfestivals() {
        return this.tickettypesperfestivals;
    }
    
    public void setTickettypesperfestivals(Set<Tickettypesperfestival> tickettypesperfestivals) {
        this.tickettypesperfestivals = tickettypesperfestivals;
    }
    public Set<Tickets> getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set<Tickets> ticketses) {
        this.ticketses = ticketses;
    }




}


